[package]
name = "jumpcut"
version = "0.2.0"
authors = ["Tim Molderez <id@timmolderez.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.1"
pancurses = "0.16"
dialoguer = "0.4.0"