[package]
name = "jumpcut"
version = "0.3.0"
authors = ["Tim Molderez <id@timmolderez.be>"]
edition = "2018"

[dependencies]
regex = "1.3.1"
dirs = "2.0.1"
pancurses = "0.16"
dialoguer = "0.4.0"

[dev-dependencies]
assert_cmd = "0.11"