[package]
name = "jumpcut"
version = "0.3.2"
authors = ["Tim Molderez <id@timmolderez.be>"]
edition = "2018"

[dependencies]
regex = "1.5.4"
dirs = "4.0.0"
pancurses = "0.17.0"
dialoguer = "0.8.0"

[dev-dependencies]
assert_cmd = "0.11"

